setwd("D:/GitHub/Ekonometria1")
data = read.csv("test.csv", sep = ";")
attach(data)
head(data)
summary(data)

hist(GDP)
density(GDP)
cor(Rank, GDP)
plot(Rank,GDP)
model_GDP = lm(GDP~Rank)
abline(model_GDP)

hist(Pop)
density(Pop)
cor(Rank,Pop)
plot(Rank, Pop)
model_Pop = lm(Pop~Rank)
abline(model_Pop)

hist(PCR)
density(PCR)
cor(Rank,PCR)
plot(Rank, PCR)
model_PCR = lm(PCR~Rank)
abline(model_PCR)